language: bash

before_script:
    - git clone https://github.com/kward/shunit2.git
    - wget https://raw.github.com/lehmannro/assert.sh/v1.1/assert.sh

script:
    - bash test/test.sh
    - bash test/extended.sh
    - bash install/doinst.sh
    - bash /usr/local/bin/deploy --version
